# Generated by Django 3.1.4 on 2021-01-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0011_captcha_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='replicated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
