# Generated by Django 3.1.4 on 2021-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0012_domain_replicated'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='replication_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
